name: "Setup Development Environment"
description: "Sets up Node.js and Python environments"
inputs:
  node-version:
    description: "Version of Node.js to use"
    required: true
    default: "16"
  python-version:
    description: "Version of Python to use"
    required: true
    default: "3.9"
outputs:
  node-path:
    description: "The path to the Node.js executable"
    value: ${{ steps.setup-node.outputs.node-path }}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        npm install
        pip install -r requirements.txt
